Palette colors
KWongEE/Color-Fu pull request #6
Opened 2018-04-27 16:17 UTC by KWongEE

Fixed issues RE: AmyLynn's feedback in PR #3

2018-04-27 18:14 UTC, bkincart requested changes

2018-04-27 18:14 UTC, bkincart commented on app/assets/stylesheets/application.css
> +}
Please remove lines 38-43 here!

2018-04-27 18:14 UTC, bkincart commented on app/controllers/api/v1/palettes_controller.rb
> +    render json: Palette.find(params[:id]), adapter: :json
You set this up in your `wrap_parameters` file already, so you don't need `, adapter: :json` on line 4 or 8 here.

2018-04-27 18:14 UTC, bkincart commented on app/controllers/api/v1/palettes_controller.rb
> +    params.require(:palette).permit(:title,:hexcode,:description)
Please add spaces between arguments here

2018-04-27 18:14 UTC, bkincart commented on app/controllers/palettes_controller.rb
> +end
Do we still need this controller if these views are being handled by React? If not, please remove necessary controller and routes

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/components/Color.js
> +// import { Link } from 'react-router'
Please remove if this isn't being used!

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/components/Color.js
> +
Please remove empty lines 5 & 10

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/components/PaletteShow.js
> +        hexcode = {palette.hexcode}
If this is multiple hexcodes I would change your prop name to be plural!

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/components/PaletteTile.js
> +  let hexcodes = props.hexcode
I would actually move your `.map` up here to keep the logic out of your JSX. Something like: 
```
let hexcodes = props.hexcode.map((hex, i) => <Color color={hex} key={i} />)
```

Then, on line 11, you can simply render `{hexcodes}`!

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +  validateHexcode(shmugana) {
Please choose a better argument name here!

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +  validateTitle(bugana) {
Same here please

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +      description: '',
Please remove description from state if you're not using it!

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +    // this.validateDescription = this.validateDescription.bind(this)
Please remove this line altogether as well

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +          // description: this.state.description
Please remove. Also, remove trailing comma on 88

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PalettesIndexContainer.js
> +
Please remove empty line!

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PalettesShowContainer.js
> +class PalettesShowContainer extends Component {
This class name should probably be singular if it's a show (i.e. `PaletteShowContainer`)

2018-04-27 18:14 UTC, bkincart commented on app/javascript/react/containers/PalettesShowContainer.js
> +    fetch(`http://localhost:3000/api/v1/palettes/${paletteId}`)
You don't want to hardcode this to localhost since it won't work in production!! You should just have it fetch to `/api/v1/palettes/${paletteId}` instead :)

2018-04-27 18:14 UTC, bkincart commented on app/models/palette.rb
> +
Remove empty line

2018-04-27 18:14 UTC, bkincart commented on app/views/layouts/application.html.erb
> +  </div>
We don't actually want to have this div live in our `application.html.erb`. Instead, we would rather have one erb template that's fully responsible for having this div. I typically call this a `static_pages` view (you'll see this as a trend/convention).

Here's what you would do to get that set up:
1. Add a route to your `routes.rb` to account for any NON-API paths. It goes at the bottom, just before the `end`, in your `routes.rb` file as follows: `get "*path", to: "static_pages#index"`
2. Add a `StaticPagesController` with an empty `def index; end`
3. Add a folder under `views` called `static_pages`
4. Add an `index.html.erb` in that folder and move lines 40-41 here into that file :)

2018-04-27 18:14 UTC, bkincart commented on config/routes.rb
> +  root 'palettes#index'
Do we need this anymore, or are all non-API pages being rendered in React?

2018-04-27 18:14 UTC, bkincart commented on config/routes.rb
> +  resources :palettes
Same here - can we remove this now that you're using React?

2018-04-27 20:13 UTC, bkincart requested changes
Followups on multiple comments

2018-04-27 20:13 UTC, bkincart commented on app/controllers/palettes_controller.rb
> +class PalettesController < ApplicationController
Can we remove this entire controller?

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/components/PaletteTile.js
> +  let hexcodes = props.hexcode
It looks like this hasn't been updated yet, please update!

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +      description: '',
Followup

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +    // this.validateDescription = this.validateDescription.bind(this)
Followup

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +  validateHexcode(shmugana) {
Followup

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +  validateTitle(bugana) {
Followup

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/containers/PaletteFormContainer.js
> +          // description: this.state.description
Followup

2018-04-27 20:13 UTC, bkincart commented on app/javascript/react/containers/PalettesShowContainer.js
> +class PalettesShowContainer extends Component {
Followup

2018-04-27 20:21 UTC, KWongEE commented on app/controllers/palettes_controller.rb
> +class PalettesController < ApplicationController
We tried and erroring. We need the file

2018-04-30 18:05 UTC, AL6981 approved these changes
Approved & merged

2018-04-30 18:05 UTC, AL6981 commented on app/javascript/react/components/Color.js
> +// import { Link } from 'react-router'
We shouldn't have any uncommented code. All PR's should be ready for production.

2018-04-30 18:05 UTC, AL6981 commented on app/javascript/react/containers/PaletteFormContainer.js
> +    // this.validateDescription = this.validateDescription.bind(this)
Remove comments.

2018-04-30 18:05 UTC, AL6981 commented on app/javascript/react/containers/PaletteFormContainer.js
> +    // This is not good enough validation but we'll come back to it
Needs to be completed before merging to master.

2018-04-30 18:05 UTC, AL6981 commented on app/assets/stylesheets/application.css
> +  /* border-radius: 40px;
Remove comments/commented code.

2018-04-30 18:10 UTC, merged